//! Generated by loom-tokens — do NOT edit by hand.
//! Re-emit via `loom egui > src/loom_tokens.rs`.
//!
//! Cross-platform mirror of the loom-tokens CSS output.
//! Requires `egui` as a dependency of the consuming crate.

#![allow(dead_code)]

use egui::Color32;

/// Light-theme palette.
pub mod color {
    use super::Color32;
    /// `primary` — primary — `hsl(220 90% 28%)`
    pub const PRIMARY: Color32 = Color32::from_rgb(7, 50, 136);
    /// `primary-fg` — primary-foreground — `#ffffff`
    pub const PRIMARY_FG: Color32 = Color32::from_rgb(255, 255, 255);
    /// `surface` — white — `#ffffff`
    pub const SURFACE: Color32 = Color32::from_rgb(255, 255, 255);
    /// `surface-muted` — slate-50 — `hsl(210 40% 98%)`
    pub const SURFACE_MUTED: Color32 = Color32::from_rgb(248, 250, 252);
    /// `ink` — slate-900 — `hsl(222 47% 11%)`
    pub const INK: Color32 = Color32::from_rgb(15, 23, 41);
    /// `ink-muted` — slate-600 — `hsl(215 16% 47%)`
    pub const INK_MUTED: Color32 = Color32::from_rgb(101, 117, 139);
    /// `border` — slate-200 — `hsl(214 32% 91%)`
    pub const BORDER: Color32 = Color32::from_rgb(225, 231, 239);
    /// `danger` — red-600 — `hsl(0 72% 51%)`
    pub const DANGER: Color32 = Color32::from_rgb(220, 40, 40);
    /// `success` — emerald-600 — `hsl(160 84% 30%)`
    pub const SUCCESS: Color32 = Color32::from_rgb(12, 141, 98);
    /// `warn` — amber-600 — `hsl(28 80% 50%)`
    pub const WARN: Color32 = Color32::from_rgb(230, 121, 25);
    /// `warn-bg` — amber-50 — `hsl(40 90% 93%)`
    pub const WARN_BG: Color32 = Color32::from_rgb(253, 243, 221);
    /// `tier-medium` — yellow-500 — `hsl(50 80% 56%)`
    pub const TIER_MEDIUM: Color32 = Color32::from_rgb(233, 203, 53);
    /// `border-strong` — slate-300 — `hsl(212 16% 82%)`
    pub const BORDER_STRONG: Color32 = Color32::from_rgb(202, 209, 216);
    /// `accent-soft` — blue-200 — `hsl(220 75% 80%)`
    pub const ACCENT_SOFT: Color32 = Color32::from_rgb(166, 191, 242);
    /// `accent-glow` — blue-100 — `hsl(220 75% 90%)`
    pub const ACCENT_GLOW: Color32 = Color32::from_rgb(210, 223, 249);
    /// `gradient-a` — blue-500 — `hsl(218 78% 56%)`
    pub const GRADIENT_A: Color32 = Color32::from_rgb(55, 119, 230);
    /// `gradient-b` — purple-500 — `hsl(269 65% 57%)`
    pub const GRADIENT_B: Color32 = Color32::from_rgb(143, 74, 217);
    /// `bg-canvas` — slate-100 — `hsl(225 33% 99%)`
    pub const BG_CANVAS: Color32 = Color32::from_rgb(252, 252, 253);
    /// `bg-overlay` — slate-200 — `hsl(220 28% 95%)`
    pub const BG_OVERLAY: Color32 = Color32::from_rgb(239, 241, 246);
}

/// Dark-theme palette mirror — same role names, dark-resolved values.
pub mod color_dark {
    use super::Color32;
    /// `primary` — primary — `hsl(220 90% 65%)`
    pub const PRIMARY: Color32 = Color32::from_rgb(85, 139, 246);
    /// `primary-fg` — slate-950 — `hsl(222 47% 6%)`
    pub const PRIMARY_FG: Color32 = Color32::from_rgb(8, 12, 22);
    /// `surface` — slate-950 — `hsl(222 47% 6%)`
    pub const SURFACE: Color32 = Color32::from_rgb(8, 12, 22);
    /// `surface-muted` — slate-900 — `hsl(222 47% 11%)`
    pub const SURFACE_MUTED: Color32 = Color32::from_rgb(15, 23, 41);
    /// `ink` — slate-50 — `hsl(210 40% 98%)`
    pub const INK: Color32 = Color32::from_rgb(248, 250, 252);
    /// `ink-muted` — slate-400 — `hsl(215 20% 65%)`
    pub const INK_MUTED: Color32 = Color32::from_rgb(148, 163, 184);
    /// `border` — slate-800 — `hsl(217 33% 18%)`
    pub const BORDER: Color32 = Color32::from_rgb(31, 42, 61);
    /// `danger` — red-400 — `hsl(0 72% 65%)`
    pub const DANGER: Color32 = Color32::from_rgb(230, 101, 101);
    /// `success` — emerald-400 — `hsl(160 84% 55%)`
    pub const SUCCESS: Color32 = Color32::from_rgb(44, 237, 172);
    /// `warn` — amber-400 — `hsl(33 100% 66%)`
    pub const WARN: Color32 = Color32::from_rgb(255, 177, 82);
    /// `warn-bg` — amber-950 — `hsl(33 50% 16%)`
    pub const WARN_BG: Color32 = Color32::from_rgb(61, 43, 20);
    /// `tier-medium` — yellow-400 — `hsl(50 75% 65%)`
    pub const TIER_MEDIUM: Color32 = Color32::from_rgb(233, 210, 99);
    /// `border-strong` — slate-700 — `hsl(218 22% 30%)`
    pub const BORDER_STRONG: Color32 = Color32::from_rgb(60, 72, 93);
    /// `accent-soft` — blue-700 — `hsl(222 41% 47%)`
    pub const ACCENT_SOFT: Color32 = Color32::from_rgb(71, 100, 169);
    /// `accent-glow` — blue-200 — `hsl(220 100% 85%)`
    pub const ACCENT_GLOW: Color32 = Color32::from_rgb(179, 204, 255);
    /// `gradient-a` — blue-400 — `hsl(218 83% 65%)`
    pub const GRADIENT_A: Color32 = Color32::from_rgb(92, 146, 240);
    /// `gradient-b` — purple-400 — `hsl(272 84% 65%)`
    pub const GRADIENT_B: Color32 = Color32::from_rgb(171, 91, 241);
    /// `bg-canvas` — slate-950 — `hsl(220 33% 6%)`
    pub const BG_CANVAS: Color32 = Color32::from_rgb(10, 14, 20);
    /// `bg-overlay` — slate-800 — `hsl(220 24% 20%)`
    pub const BG_OVERLAY: Color32 = Color32::from_rgb(39, 47, 63);
}

/// Spacing scale. `*_REM` for layout that multiplies by base font size,
/// `*_PX` pre-resolved at the 16 px design root.
pub mod space {
    /// step 0 — 0rem (0px @16)
    pub const S0_REM: f32 = 0_f32;
    pub const S0_PX: u32 = 0;
    /// step 1 — 0.25rem (4px @16)
    pub const S1_REM: f32 = 0.25_f32;
    pub const S1_PX: u32 = 4;
    /// step 2 — 0.5rem (8px @16)
    pub const S2_REM: f32 = 0.5_f32;
    pub const S2_PX: u32 = 8;
    /// step 3 — 0.75rem (12px @16)
    pub const S3_REM: f32 = 0.75_f32;
    pub const S3_PX: u32 = 12;
    /// step 4 — 1rem (16px @16)
    pub const S4_REM: f32 = 1_f32;
    pub const S4_PX: u32 = 16;
    /// step 6 — 1.5rem (24px @16)
    pub const S6_REM: f32 = 1.5_f32;
    pub const S6_PX: u32 = 24;
    /// step 8 — 2rem (32px @16)
    pub const S8_REM: f32 = 2_f32;
    pub const S8_PX: u32 = 32;
    /// step 12 — 3rem (48px @16)
    pub const S12_REM: f32 = 3_f32;
    pub const S12_PX: u32 = 48;
    /// step 16 — 4rem (64px @16)
    pub const S16_REM: f32 = 4_f32;
    pub const S16_PX: u32 = 64;
    /// step 24 — 6rem (96px @16)
    pub const S24_REM: f32 = 6_f32;
    pub const S24_PX: u32 = 96;
}

/// Breakpoints in pixel widths.
pub mod breakpoint {
    pub const SM: u32 = 640;
    pub const MD: u32 = 768;
    pub const LG: u32 = 1024;
    pub const XL: u32 = 1280;
}

/// Border radii. Native px values pre-resolved at the 16 px design root.
pub mod radius {
    /// 0 (none)
    pub const NONE: f32 = 0_f32;
    /// 0.25rem (sm)
    pub const SM: f32 = 4_f32;
    /// 0.5rem (md)
    pub const MD: f32 = 8_f32;
    /// 0.75rem (lg)
    pub const LG: f32 = 12_f32;
    /// 1rem (xl)
    pub const XL: f32 = 16_f32;
    /// 9999px (full)
    pub const FULL: f32 = 9999_f32;
}
