//! Theme & design system for the PlausiDen suite.
//!
//! The goal is "sexy as hell": generous whitespace, a distinctive
//! palette, a clean typographic hierarchy, soft depth via shadows,
//! and gradient accents that read as premium rather than gaudy.
//!
//! The palette is intentionally shared across PlausiDen GUI apps so
//! that Atrium, Sentinel, Marketplace, and the rest all feel like
//! parts of the same product.
//!
//! ## Loom-tokens sourcing
//!
//! Several `Palette` fields are sourced from `crate::loom_tokens`
//! (generated by `loom egui` from PlausiDen-Loom) so a token edit in
//! Loom propagates to Atrium on the next regeneration. Fields not
//! yet in Loom (the gradient pair, the warn channel, the
//! importance-tier swatches) stay native pending an upstream Loom
//! palette extension — see task #72 in the tracker.

use egui::{Color32, FontFamily, FontId, Shadow, Style, TextStyle, Visuals};
use serde::{Deserialize, Serialize};

use crate::loom_tokens::{color as loom_light, color_dark as loom_dark};

/// User's preferred theme mode.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ThemeMode {
    Dark,
    Light,
    Auto,
}

impl Default for ThemeMode {
    fn default() -> Self {
        ThemeMode::Auto
    }
}

impl ThemeMode {
    pub const ALL: [ThemeMode; 3] = [ThemeMode::Dark, ThemeMode::Light, ThemeMode::Auto];

    pub fn label(&self) -> &'static str {
        match self {
            ThemeMode::Dark => "Dark",
            ThemeMode::Light => "Light",
            ThemeMode::Auto => "Auto",
        }
    }
}

/// Resolved palette after Auto has been matched to a concrete value.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Resolved {
    Dark,
    Light,
}

pub fn resolve(mode: ThemeMode, system_prefers_dark: bool) -> Resolved {
    match mode {
        ThemeMode::Dark => Resolved::Dark,
        ThemeMode::Light => Resolved::Light,
        ThemeMode::Auto => {
            if system_prefers_dark {
                Resolved::Dark
            } else {
                Resolved::Light
            }
        }
    }
}

/// The premium PlausiDen palette.
#[allow(dead_code)]
pub struct Palette {
    // Surfaces
    pub bg: Color32,
    pub bg_panel: Color32,
    pub bg_elevated: Color32,
    pub bg_overlay: Color32,
    pub border: Color32,
    pub border_strong: Color32,

    // Text
    pub text: Color32,
    pub text_dim: Color32,
    pub text_subtle: Color32,

    // Brand + states
    pub accent: Color32,
    pub accent_soft: Color32,
    pub accent_glow: Color32,
    pub gradient_a: Color32,
    pub gradient_b: Color32,
    pub ok: Color32,
    pub warn: Color32,
    pub warn_bg: Color32,
    pub critical: Color32,

    // Importance tiers
    pub tier_critical: Color32,
    pub tier_high: Color32,
    pub tier_medium: Color32,
    pub tier_low: Color32,
    pub tier_trash: Color32,
}

impl Palette {
    /// Dark-theme palette. Every field is loom-sourced — no inline
    /// Color32 literals. `text_subtle` is the only field that
    /// doesn't have a 1:1 loom role yet; map it to ink_muted (the
    /// closest equivalent) until a future palette extension splits
    /// the muted scale into two stops.
    pub const DARK: Palette = Palette {
        bg: loom_dark::BG_CANVAS,
        bg_panel: loom_dark::SURFACE,
        bg_elevated: loom_dark::SURFACE_MUTED,
        bg_overlay: loom_dark::BG_OVERLAY,
        border: loom_dark::BORDER,
        border_strong: loom_dark::BORDER_STRONG,

        text: loom_dark::INK,
        text_dim: loom_dark::INK_MUTED,
        text_subtle: loom_dark::INK_MUTED,

        accent: loom_dark::PRIMARY,
        accent_soft: loom_dark::ACCENT_SOFT,
        accent_glow: loom_dark::ACCENT_GLOW,
        gradient_a: loom_dark::GRADIENT_A,
        gradient_b: loom_dark::GRADIENT_B,
        ok: loom_dark::SUCCESS,
        warn: loom_dark::WARN,
        warn_bg: loom_dark::WARN_BG,
        critical: loom_dark::DANGER,

        tier_critical: loom_dark::DANGER,
        tier_high: loom_dark::WARN,
        tier_medium: loom_dark::TIER_MEDIUM,
        tier_low: loom_dark::PRIMARY,
        tier_trash: loom_dark::SUCCESS,
    };

    /// Light-theme palette — fully loom-sourced mirror of DARK.
    pub const LIGHT: Palette = Palette {
        bg: loom_light::BG_CANVAS,
        bg_panel: loom_light::SURFACE,
        bg_elevated: loom_light::SURFACE_MUTED,
        bg_overlay: loom_light::BG_OVERLAY,
        border: loom_light::BORDER,
        border_strong: loom_light::BORDER_STRONG,

        text: loom_light::INK,
        text_dim: loom_light::INK_MUTED,
        text_subtle: loom_light::INK_MUTED,

        accent: loom_light::PRIMARY,
        accent_soft: loom_light::ACCENT_SOFT,
        accent_glow: loom_light::ACCENT_GLOW,
        gradient_a: loom_light::GRADIENT_A,
        gradient_b: loom_light::GRADIENT_B,
        ok: loom_light::SUCCESS,
        warn: loom_light::WARN,
        warn_bg: loom_light::WARN_BG,
        critical: loom_light::DANGER,

        tier_critical: loom_light::DANGER,
        tier_high: loom_light::WARN,
        tier_medium: loom_light::TIER_MEDIUM,
        tier_low: loom_light::PRIMARY,
        tier_trash: loom_light::SUCCESS,
    };

    pub fn for_resolved(resolved: Resolved) -> &'static Palette {
        match resolved {
            Resolved::Dark => &Palette::DARK,
            Resolved::Light => &Palette::LIGHT,
        }
    }
}

/// Design tokens — spacing, radii, typography sizes.
#[allow(dead_code)]
pub mod tokens {
    pub const SPACE_XS: f32 = 4.0;
    pub const SPACE_SM: f32 = 8.0;
    pub const SPACE_MD: f32 = 12.0;
    pub const SPACE_LG: f32 = 18.0;
    pub const SPACE_XL: f32 = 28.0;
    pub const SPACE_XXL: f32 = 44.0;

    pub const RADIUS_SM: f32 = 6.0;
    pub const RADIUS_MD: f32 = 10.0;
    pub const RADIUS_LG: f32 = 16.0;
    pub const RADIUS_PILL: f32 = 999.0;

    pub const FONT_DISPLAY: f32 = 34.0;
    pub const FONT_H1: f32 = 24.0;
    pub const FONT_H2: f32 = 18.0;
    pub const FONT_BODY: f32 = 14.5;
    pub const FONT_SMALL: f32 = 12.0;
    pub const FONT_TINY: f32 = 10.5;
    pub const FONT_MONO: f32 = 13.0;
}

/// Custom text styles available via TextStyle::Name.
pub fn text_styles() -> std::collections::BTreeMap<TextStyle, FontId> {
    use tokens::*;
    let mut m = std::collections::BTreeMap::new();
    m.insert(
        TextStyle::Heading,
        FontId::new(FONT_H1, FontFamily::Proportional),
    );
    m.insert(
        TextStyle::Body,
        FontId::new(FONT_BODY, FontFamily::Proportional),
    );
    m.insert(
        TextStyle::Button,
        FontId::new(FONT_BODY, FontFamily::Proportional),
    );
    m.insert(
        TextStyle::Small,
        FontId::new(FONT_SMALL, FontFamily::Proportional),
    );
    m.insert(
        TextStyle::Monospace,
        FontId::new(FONT_MONO, FontFamily::Monospace),
    );
    m.insert(
        TextStyle::Name("Display".into()),
        FontId::new(FONT_DISPLAY, FontFamily::Proportional),
    );
    m.insert(
        TextStyle::Name("H2".into()),
        FontId::new(FONT_H2, FontFamily::Proportional),
    );
    m.insert(
        TextStyle::Name("Tiny".into()),
        FontId::new(FONT_TINY, FontFamily::Proportional),
    );
    m
}

/// Apply the Atrium theme to an egui context.
pub fn apply(ctx: &egui::Context, resolved: Resolved) {
    let palette = Palette::for_resolved(resolved);
    let mut style = (*ctx.style()).clone();
    style.text_styles = text_styles();
    install_visuals(&mut style, palette, resolved);
    install_spacing(&mut style);
    ctx.set_style(style);
}

fn install_visuals(style: &mut Style, p: &Palette, resolved: Resolved) {
    let mut v = match resolved {
        Resolved::Dark => Visuals::dark(),
        Resolved::Light => Visuals::light(),
    };
    v.override_text_color = Some(p.text);
    v.panel_fill = p.bg;
    v.window_fill = p.bg_panel;
    v.extreme_bg_color = p.bg;
    v.faint_bg_color = p.bg_panel;
    v.code_bg_color = p.bg_elevated;
    v.hyperlink_color = p.accent;

    // Noninteractive: panel headers, static labels.
    v.widgets.noninteractive.bg_fill = p.bg_panel;
    v.widgets.noninteractive.bg_stroke = egui::Stroke::new(1.0, p.border);
    v.widgets.noninteractive.fg_stroke = egui::Stroke::new(1.0, p.text_dim);
    v.widgets.noninteractive.rounding = egui::Rounding::same(tokens::RADIUS_MD);

    // Inactive buttons / fields: clear but elevated.
    v.widgets.inactive.bg_fill = p.bg_elevated;
    v.widgets.inactive.weak_bg_fill = p.bg_panel;
    v.widgets.inactive.bg_stroke = egui::Stroke::new(1.0, p.border);
    v.widgets.inactive.fg_stroke = egui::Stroke::new(1.0, p.text);
    v.widgets.inactive.rounding = egui::Rounding::same(tokens::RADIUS_MD);
    v.widgets.inactive.expansion = 0.0;

    // Hover: accent-tinted.
    v.widgets.hovered.bg_fill = p.accent_soft;
    v.widgets.hovered.weak_bg_fill = p.bg_overlay;
    v.widgets.hovered.bg_stroke = egui::Stroke::new(1.2, p.accent);
    v.widgets.hovered.fg_stroke = egui::Stroke::new(1.5, p.text);
    v.widgets.hovered.rounding = egui::Rounding::same(tokens::RADIUS_MD);
    v.widgets.hovered.expansion = 0.0;

    // Active: pressed state.
    v.widgets.active.bg_fill = p.accent;
    v.widgets.active.weak_bg_fill = p.accent_soft;
    v.widgets.active.bg_stroke = egui::Stroke::new(1.5, p.accent);
    v.widgets.active.fg_stroke = egui::Stroke::new(2.0, Color32::WHITE);
    v.widgets.active.rounding = egui::Rounding::same(tokens::RADIUS_MD);
    v.widgets.active.expansion = 0.0;

    v.selection.bg_fill = p.accent_soft;
    v.selection.stroke = egui::Stroke::new(1.5, p.accent);

    v.window_rounding = egui::Rounding::same(tokens::RADIUS_LG);
    v.menu_rounding = egui::Rounding::same(tokens::RADIUS_MD);

    v.window_shadow = Shadow {
        offset: egui::vec2(0.0, 8.0),
        blur: 24.0,
        spread: 0.0,
        color: Color32::from_black_alpha(match resolved {
            Resolved::Dark => 140,
            Resolved::Light => 40,
        }),
    };
    v.popup_shadow = Shadow {
        offset: egui::vec2(0.0, 4.0),
        blur: 16.0,
        spread: 0.0,
        color: Color32::from_black_alpha(match resolved {
            Resolved::Dark => 100,
            Resolved::Light => 30,
        }),
    };

    style.visuals = v;
}

fn install_spacing(style: &mut Style) {
    use tokens::*;
    style.spacing.item_spacing = egui::vec2(SPACE_MD, SPACE_SM + 2.0);
    style.spacing.button_padding = egui::vec2(16.0, 10.0);
    style.spacing.menu_margin = egui::Margin::same(SPACE_SM);
    style.spacing.window_margin = egui::Margin::same(SPACE_LG);
    style.spacing.indent = 20.0;
    style.spacing.interact_size = egui::vec2(40.0, 30.0);
    style.spacing.scroll.bar_width = 12.0;
    style.spacing.scroll.bar_inner_margin = 2.0;
    style.spacing.scroll.bar_outer_margin = 2.0;
}

/// Linearly interpolate two RGBA colours.
pub fn lerp_color(a: Color32, b: Color32, t: f32) -> Color32 {
    let t = t.clamp(0.0, 1.0);
    Color32::from_rgba_unmultiplied(
        lerp_u8(a.r(), b.r(), t),
        lerp_u8(a.g(), b.g(), t),
        lerp_u8(a.b(), b.b(), t),
        lerp_u8(a.a(), b.a(), t),
    )
}

fn lerp_u8(a: u8, b: u8, t: f32) -> u8 {
    (a as f32 * (1.0 - t) + b as f32 * t).round() as u8
}

/// Paint a vertical linear gradient across `rect`.
pub fn paint_vertical_gradient(
    painter: &egui::Painter,
    rect: egui::Rect,
    top: Color32,
    bottom: Color32,
) {
    let steps = (rect.height() as usize).max(1);
    for i in 0..steps {
        let t = i as f32 / (steps - 1).max(1) as f32;
        let color = lerp_color(top, bottom, t);
        let row = egui::Rect::from_min_size(
            rect.left_top() + egui::vec2(0.0, i as f32),
            egui::vec2(rect.width(), 1.0),
        );
        painter.rect_filled(row, egui::Rounding::ZERO, color);
    }
}

/// Paint a horizontal linear gradient across `rect`.
pub fn paint_horizontal_gradient(
    painter: &egui::Painter,
    rect: egui::Rect,
    left: Color32,
    right: Color32,
) {
    let steps = (rect.width() as usize).max(1);
    for i in 0..steps {
        let t = i as f32 / (steps - 1).max(1) as f32;
        let color = lerp_color(left, right, t);
        let col = egui::Rect::from_min_size(
            rect.left_top() + egui::vec2(i as f32, 0.0),
            egui::vec2(1.0, rect.height()),
        );
        painter.rect_filled(col, egui::Rounding::ZERO, color);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_resolve_modes() {
        assert_eq!(resolve(ThemeMode::Dark, false), Resolved::Dark);
        assert_eq!(resolve(ThemeMode::Light, true), Resolved::Light);
        assert_eq!(resolve(ThemeMode::Auto, true), Resolved::Dark);
        assert_eq!(resolve(ThemeMode::Auto, false), Resolved::Light);
    }

    #[test]
    fn test_labels() {
        for m in ThemeMode::ALL {
            assert!(!m.label().is_empty());
        }
    }

    #[test]
    fn test_palette_distinct() {
        assert_ne!(Palette::DARK.bg, Palette::LIGHT.bg);
        assert_ne!(Palette::DARK.text, Palette::LIGHT.text);
    }

    #[test]
    fn test_lerp_color() {
        let a = Color32::from_rgb(0, 0, 0);
        let b = Color32::from_rgb(255, 255, 255);
        let mid = lerp_color(a, b, 0.5);
        assert!((mid.r() as i32 - 128).abs() <= 1);
    }

    #[test]
    fn test_lerp_color_endpoints() {
        let a = Color32::from_rgb(10, 20, 30);
        let b = Color32::from_rgb(200, 210, 220);
        assert_eq!(lerp_color(a, b, 0.0).r(), 10);
        assert_eq!(lerp_color(a, b, 1.0).r(), 200);
    }
}
